### ISSUE TITLE
Failed to execute script?

### ISSUE THREAD

**Issue by mikepiman** [bradenhilton/yt-dlp-FixupMtime#9]
Hi, I simply ran this, and got this:

`yt-dlp https://youtu.be/FDqUDoOhKoA --use-postprocessor FixupMtime:mtime_key=upload_date`

`Traceback (most recent call last):`
`  File "yt_dlp\__main__.py", line 17, in <module>`
`  File "yt_dlp\__init__.py", line 1081, in main`
`  File "yt_dlp\__init__.py", line 979, in _real_main`
`  File "yt_dlp\YoutubeDL.py", line 809, in __init__`
`  File "yt_dlp\postprocessor\__init__.py", line 42, in get_postprocessor`
`KeyError: 'FixupMtimePP'`
`[12900] Failed to execute script '__main__' due to unhandled exception!`

yt-dlp and FixupMtime are latest version.  A different [integer] appears every time, below about 20,000.

**Comment by bradenhilton** [comment]
Where did you install the plugin?

**Comment by mikepiman** [comment]
FixupMtime is installed in D:\Python\Python310\Lib\site-packages
and yt-dlp is in C:\Program Files (x86)\Batchenc

on Windows 10 x64

**Comment by bradenhilton** [comment]
How did you install yt-dlp?

Something about your setup is preventing yt-dlp from finding the plugin.

```console
❯ pipx install "yt-dlp[default,curl-cffi]"

❯ pipx inject yt-dlp https://github.com/bradenhilton/yt-dlp-FixupMtime/archive/master.zip

❯ yt-dlp --verbose --ignore-config https://youtu.be/FDqUDoOhKoA --use-postprocessor FixupMtime:mtime_key=upload_date
[debug] Command-line config: ['--verbose', '--ignore-config', 'https://youtu.be/FDqUDoOhKoA', '--use-postprocessor', 'FixupMtime:mtime_key=upload_date']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.01 from yt-dlp/yt-dlp [ffd7781d6] (pip)
[debug] Python 3.12.4 (CPython AMD64 64bit) - Windows-11-10.0.22631-SP0 (OpenSSL 3.0.13 30 Jan 2024)
[debug] exe versions: ffmpeg 7.0.1-full_build-www.gyan.dev (setts), ffprobe 7.0.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.3, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Post-Processor Plugins: FixupMtimePP
[debug] Plugin directories: ['C:\\Users\\User\\pipx\\venvs\\yt-dlp\\Lib\\site-packages\\yt_dlp_plugins']
[debug] Loaded 1830 extractors
[youtube] Extracting URL: https://youtu.be/FDqUDoOhKoA
[youtube] FDqUDoOhKoA: Downloading webpage
[youtube] FDqUDoOhKoA: Downloading ios player API JSON
[youtube] FDqUDoOhKoA: Downloading tv player API JSON
[debug] [youtube] Extracting signature function js_d2e656ee_111
[debug] Loading youtube-sigfuncs.js_d2e656ee_111 from cache
[youtube] FDqUDoOhKoA: Downloading player d2e656ee
[debug] Saving youtube-nsig.d2e656ee to cache
[debug] [youtube] Decrypted nsig wiN2Cu0jar2uGl6H => AOGVdHFI6xNoyA
[debug] Loading youtube-nsig.d2e656ee from cache
[debug] [youtube] Decrypted nsig -w9Gh-vbT-dPknqZ => OeyogLrHayIMpQ
[debug] [youtube] Extracting signature function js_d2e656ee_107
[debug] Loading youtube-sigfuncs.js_d2e656ee_107 from cache
[youtube] FDqUDoOhKoA: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] FDqUDoOhKoA: Downloading 1 format(s): 616+251
[debug] Invoking hlsnative downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1722638800/ei/cA2tZqmmHqWFp-oP9OO9-QU/ip/86.4.177.173/id/143a940e83a12a80/itag/616/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D35272422%3Bdur%3D164.000%3Bgir%3Dyes%3Bitag%3D356%3Blmt%3D1705662086720341/rqh/1/hls_chunk_host/rr6---sn-8pgbpohxqp5-h5or.googlevideo.com/xpc/EgVo2aDSNQ%3D%3D/mh/lm/mm/31,29/mn/sn-8pgbpohxqp5-h5or,sn-aigl6nz7/ms/au,rdu/mv/m/mvi/6/pl/22/force_finished/1/initcwndbps/2288750/vprv/1/playlist_type/DVR/dover/13/txp/4532434/mt/1722616656/fvip/4/short_key/1/keepalive/yes/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,rqh,xpc,force_finished,vprv,playlist_type/sig/AJfQdSswRAIgFo3nNNKfHLamJadYXjFoahb_pmVRWi8hYL-R0U6LfAsCIAb-9zaGvVG0jdLJMjllDbOxNDk6KxH8h5QGWqyy2wYD/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AGtxev0wRAIgTzZI7r7le_H9F7caScoT6PzDK0trw8KVKmrboeJQf_ICIFATJNqc0ZczFZxZtpCJraRAZN32foKsQd20Q45sgTpD/playlist/index.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 32
[download] Destination: 絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].f616.mp4
[debug] File locking is not supported. Proceeding without locking
[download] 100% of   33.66MiB in 00:00:04 at 8.33MiB/s
[debug] Invoking http downloader on "https://rr6---sn-8pgbpohxqp5-h5or.googlevideo.com/videoplayback?expire=1722638800&ei=cA2tZu3ZI_akvdIP35KEsQ0&ip=86.4.177.173&id=o-ABajm2ts7juGEI58deFxdET0_31f_0-UhuiNq8RpXD0u&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=lm&mm=31%2C29&mn=sn-8pgbpohxqp5-h5or%2Csn-aigzrnsz&ms=au%2Crdu&mv=m&mvi=6&pl=22&initcwndbps=2288750&bui=AXc671JkmkP5BwJJIuTA-93TUQeX1aGEseR9VIH1vlEh1lQm9xvP6jpcUpnk6kVk0axC_EcMDcigcINY&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=LjhEJiUzYzZ8w6E53oVdv14Q&rqh=1&gir=yes&clen=2552022&dur=164.021&lmt=1714551709422426&mt=1722616656&fvip=2&keepalive=yes&lmw=1&c=TVHTML5&sefc=1&txp=4502434&n=OeyogLrHayIMpQ&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRQIhAKY0uFeXgJvyiQmYGrxrGoOFYc47eQrwX2uYAHmX7KL4AiAxoeTpcsvLJfZRzBc7i_UJdZYQ6GZEWht0uccOrOZcIw%3D%3D&sig=AJfQdSswRAIgcZyRAP0kVbJ1uDY0tYgAWv1r0KVrkt1Gusm0mjt6UKwCICLZQ4dqAiJ5IHDDDLH6MdhweccsoN-ZB3iYZ0nsKOXT"
[download] Destination: 絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].f251.webm
[download] 100% of    2.43MiB in 00:00:00 at 15.30MiB/s
[Merger] Merging formats into "絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i "file:絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].f616.mp4" -i "file:絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].f251.webm" -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart "file:絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].temp.webm"
Deleting original file 絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].f251.webm (pass -k to keep)
Deleting original file 絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].f616.mp4 (pass -k to keep)
[FixupMtime] Setting mtime of files to `upload_date` (2023-05-20T00:00:00)
```

If you don't want to change your yt-dlp installation, perhaps try one of the [alternative plugin installation methods](https://github.com/yt-dlp/yt-dlp#installing-plugins).

**Comment by mikepiman** [comment]
That's right; it works now!

I was using the "pip" script as recommended in FixupMtime's Readme,

but instead, thanks to your posted link, I installed FixupMtime's .py script into "<yt-dlp's dir>/yt-dlp-plugins/postprocessor/yt_dlp_plugins/postprocessor/",

which seems repetitive and counterintuitive but works!

**Comment by mikepiman** [comment]
That's right; it works now!

I was using the "pip" script as recommended in FixupMtime's Readme,

but instead, thanks to your posted link, I installed FixupMtime's .py script into "<yt-dlp's dir>/yt-dlp-plugins/postprocessor/yt_dlp_plugins/postprocessor/",

which seems repetitive and counterintuitive but works!

**Comment by mikepiman** [comment]
That's right; it works now!

I was using the "pip" script as recommended in FixupMtime's Readme,

but instead, thanks to your posted link, I installed FixupMtime's .py script into "<yt-dlp's dir>/yt-dlp-plugins/postprocessor/yt_dlp_plugins/postprocessor/",

which seems repetitive and counterintuitive but works!


I _would_ like to be able to update it automatically using "pip", but apparently cannot do that now.

**Comment by bradenhilton** [comment]
I don't think this is an issue with the plugin, as it doesn't do anything to alter the way plugins are loaded.

I think this is an issue with the method you used to install yt-dlp being incompatible with the pip installation of the plugin. They are located in different drives for starters.

My *guess* is that it would work as expected if you install both yt-dlp and the plugin with pip.

You may want to ask on the yt-dlp repo for clarification.
